#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Minimal NemoClaw-compatible entrypoint for the financial Hermes sandbox.

set -euo pipefail

_SANDBOX_INIT="/usr/local/lib/nemoclaw/sandbox-init.sh"
if [[ ! -f "$_SANDBOX_INIT" ]]; then
  _SANDBOX_INIT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../scripts/lib/sandbox-init.sh"
fi
# shellcheck disable=SC1090
source "$_SANDBOX_INIT"

if ! ulimit -Su 512 2>/dev/null; then
  echo "[SECURITY] Could not set soft process limit" >&2
fi
if ! ulimit -Hu 512 2>/dev/null; then
  echo "[SECURITY] Could not set hard process limit" >&2
fi

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

prepare_restricted_log() {
  local path="$1" mode="${2:-600}" dir base temporary
  dir="$(dirname "$path")"
  base="$(basename "$path")"
  temporary="$(mktemp "${dir}/.${base}.tmp.XXXXXX")"
  : >"$temporary"
  chmod "$mode" "$temporary"
  mv -f "$temporary" "$path"
}

_START_LOG="/tmp/nemoclaw-start.log"
prepare_restricted_log "$_START_LOG"
exec > >(tee -a "$_START_LOG") 2> >(tee -a "$_START_LOG" >&2)

drop_capabilities /usr/local/bin/nemoclaw-start "$@"

# Normalize OpenShell's `env ... nemoclaw-start` self-wrapper form.
if [[ "${1:-}" == "env" ]]; then
  _raw_args=("$@")
  _wrapper_index=""
  for ((i = 1; i < ${#_raw_args[@]}; i += 1)); do
    case "${_raw_args[$i]}" in
      *=*) ;;
      nemoclaw-start | /usr/local/bin/nemoclaw-start)
        _wrapper_index="$i"
        break
        ;;
      *) break ;;
    esac
  done
  if [[ -n "$_wrapper_index" ]]; then
    for ((i = 1; i < _wrapper_index; i += 1)); do
      export "${_raw_args[$i]}"
    done
    set -- "${_raw_args[@]:$((_wrapper_index + 1))}"
  fi
fi
case "${1:-}" in
  nemoclaw-start | /usr/local/bin/nemoclaw-start) shift ;;
esac
NEMOCLAW_CMD=("$@")

PUBLIC_PORT=8642
INTERNAL_PORT=18642
HERMES_IMMUTABLE="/sandbox/.hermes"
HERMES_WRITABLE="/sandbox/.hermes-data"
HERMES_HASH_FILE="${HERMES_IMMUTABLE}/.config-hash"
RELAY_CONFIG="/etc/nemo-relay/config/plugins.toml"

# Hermes's native Relay plugin owns this per-session subscriber. Keeping ATIF
# out of the process-level plugins.toml lets on_session_end refresh the file
# after every completed API or chat turn instead of waiting for process exit.
export HERMES_NEMO_RELAY_ATIF_ENABLED=1
export HERMES_NEMO_RELAY_ATIF_OUTPUT_DIRECTORY=/sandbox/.hermes-data/atif
export HERMES_NEMO_RELAY_ATIF_FILENAME_TEMPLATE='financial-assistant-atif-{session_id}.json'
export HERMES_NEMO_RELAY_ATIF_AGENT_NAME='Financial Assistant'
export HERMES_NEMO_RELAY_ATIF_AGENT_VERSION=0.20.0

deploy_config_to_writable() {
  cp "${HERMES_IMMUTABLE}/config.yaml" "${HERMES_WRITABLE}/config.yaml"
  cp "${HERMES_IMMUTABLE}/.env" "${HERMES_WRITABLE}/.env"
  chmod 600 "${HERMES_WRITABLE}/config.yaml" "${HERMES_WRITABLE}/.env"
}

PROXY_HOST="${NEMOCLAW_PROXY_HOST:-10.200.0.1}"
PROXY_PORT="${NEMOCLAW_PROXY_PORT:-3128}"
_PROXY_URL="http://${PROXY_HOST}:${PROXY_PORT}"
_NO_PROXY="localhost,127.0.0.1,::1,${PROXY_HOST}"
export HTTP_PROXY="$_PROXY_URL" HTTPS_PROXY="$_PROXY_URL" NO_PROXY="$_NO_PROXY"
export http_proxy="$_PROXY_URL" https_proxy="$_PROXY_URL" no_proxy="$_NO_PROXY"

if [[ -n "${SSL_CERT_FILE:-}" && -f "${SSL_CERT_FILE}" ]]; then
  export CURL_CA_BUNDLE="${CURL_CA_BUNDLE:-$SSL_CERT_FILE}"
  export REQUESTS_CA_BUNDLE="${REQUESTS_CA_BUNDLE:-$SSL_CERT_FILE}"
  export GIT_SSL_CAINFO="${GIT_SSL_CAINFO:-$SSL_CERT_FILE}"
fi

_PROXY_ENV_FILE="/tmp/nemoclaw-proxy-env.sh"
{
  cat <<PROXYEOF
# Generated by the immutable sandbox entrypoint.
export HTTP_PROXY="$_PROXY_URL"
export HTTPS_PROXY="$_PROXY_URL"
export NO_PROXY="$_NO_PROXY"
export http_proxy="$_PROXY_URL"
export https_proxy="$_PROXY_URL"
export no_proxy="$_NO_PROXY"
export HERMES_HOME="${HERMES_WRITABLE}"
export HERMES_NEMO_RELAY_PLUGINS_TOML="${RELAY_CONFIG}"
export HERMES_NEMO_RELAY_ATIF_ENABLED=1
export HERMES_NEMO_RELAY_ATIF_OUTPUT_DIRECTORY=/sandbox/.hermes-data/atif
export HERMES_NEMO_RELAY_ATIF_FILENAME_TEMPLATE='financial-assistant-atif-{session_id}.json'
export HERMES_NEMO_RELAY_ATIF_AGENT_NAME='Financial Assistant'
export HERMES_NEMO_RELAY_ATIF_AGENT_VERSION=0.20.0
export XDG_CONFIG_HOME="/etc/nemo-relay/xdg"
export TERMINAL_CWD="/sandbox"
export PATH="/usr/local/lib/nemoclaw/bin:\$PATH"
export HERMES_TUI_THEME=dark
export HERMES_DISABLE_LAZY_INSTALLS=1
PROXYEOF
  cat <<'TUIEOF'
if [ -s /opt/hermes/ui-tui/dist/entry.js ]; then
  export HERMES_TUI_DIR=/opt/hermes/ui-tui
fi
TUIEOF
  for name in SSL_CERT_FILE CURL_CA_BUNDLE REQUESTS_CA_BUNDLE GIT_SSL_CAINFO SEC_USER_AGENT; do
    value="${!name:-}"
    [[ -n "$value" ]] && printf 'export %s=%q\n' "$name" "$value"
  done
} | emit_sandbox_sourced_file "$_PROXY_ENV_FILE"

prepare_runtime() {
  prepare_restricted_log /tmp/gateway.log
  # shellcheck disable=SC2119
  validate_tmp_permissions
  mkdir -p /sandbox/.hermes-data/atif
  [[ -r "$RELAY_CONFIG" ]] || {
    echo "[nemo-relay] Native configuration is missing: $RELAY_CONFIG" >&2
    return 1
  }
  /opt/hermes/.venv/bin/python - <<'PY'
import tomllib
from nemo_relay import plugin

with open("/etc/nemo-relay/config/plugins.toml", "rb") as handle:
    report = plugin.validate(tomllib.load(handle))
if report["diagnostics"]:
    raise SystemExit(f"invalid native Relay config: {report['diagnostics']}")
PY
}

launch_gateway() {
  (
    cd /etc/nemo-relay/runtime
    exec env \
      HERMES_HOME="$HERMES_WRITABLE" \
      HERMES_NEMO_RELAY_PLUGINS_TOML="$RELAY_CONFIG" \
      XDG_CONFIG_HOME=/etc/nemo-relay/xdg \
      TERMINAL_CWD=/sandbox \
      API_SERVER_KEY=nemoclaw-internal \
      HTTPS_PROXY="$_PROXY_URL" HTTP_PROXY="$_PROXY_URL" \
      https_proxy="$_PROXY_URL" http_proxy="$_PROXY_URL" \
      hermes gateway run
  ) >>/tmp/gateway.log 2>&1 &
  GATEWAY_PID=$!
  echo "[gateway] Hermes launched (pid $GATEWAY_PID)" >&2
}

start_log_stream() {
  { tail -n +1 -F /tmp/gateway.log 2>/dev/null | sed -u 's/^/[gateway] /' >&2; } &
  LOG_TAIL_PID=$!
}

start_forwarder() {
  local attempts=0
  while [[ "$attempts" -lt 60 ]]; do
    if ss -tln 2>/dev/null | grep -q "127.0.0.1:${INTERNAL_PORT}"; then
      break
    fi
    sleep 1
    attempts=$((attempts + 1))
  done
  ss -tln 2>/dev/null | grep -q "127.0.0.1:${INTERNAL_PORT}" || {
    echo "[gateway] Hermes API did not listen on $INTERNAL_PORT" >&2
    return 1
  }
  socat TCP-LISTEN:"${PUBLIC_PORT}",bind=0.0.0.0,fork,reuseaddr \
    TCP:127.0.0.1:"${INTERNAL_PORT}" >/dev/null 2>&1 &
  SOCAT_PID=$!
  echo "[gateway] Sandbox API forward ready on :${PUBLIC_PORT}" >&2
}

echo "Starting Financial Assistant as $(id -un) (uid=$(id -u))" >&2
export HOME=/sandbox
export HERMES_HOME="$HERMES_WRITABLE"

verify_config_integrity "$HERMES_IMMUTABLE" "$HERMES_HASH_FILE" || {
  echo "[SECURITY] Immutable Hermes configuration failed verification" >&2
  exit 1
}
deploy_config_to_writable

if [[ ${#NEMOCLAW_CMD[@]} -gt 0 ]]; then
  exec "${NEMOCLAW_CMD[@]}"
fi

prepare_runtime
launch_gateway
start_log_stream
start_forwarder

# shellcheck disable=SC2034  # read by cleanup_on_signal from sandbox-init.sh
SANDBOX_CHILD_PIDS=("$GATEWAY_PID" "$LOG_TAIL_PID" "$SOCAT_PID")
# shellcheck disable=SC2034  # read by cleanup_on_signal from sandbox-init.sh
SANDBOX_WAIT_PID="$GATEWAY_PID"
trap cleanup_on_signal SIGTERM SIGINT

echo "[gateway] Host access requires an OpenShell loopback forward to 127.0.0.1:${PUBLIC_PORT}" >&2
wait "$GATEWAY_PID"
